using Android.Content;
using PolyhydraGames.Core.Maui.Services.Abstract;

namespace PolyhydraGames.Core.Maui.Services.Email;

/// <summary>
///     Email service implementation
/// </summary>
public class EmailService : ActivityServiceBase, IEmailService
{
    /// <summary>
    /// </summary>
    /// <param name="locator"></param>
    public EmailService(ICurrentActivityLocator locator) : base(locator)
    {
        }


    /// <summary>
    ///     Requests a new email to be generated by the Android device.
    /// </summary>
    /// <param name="address">The address of the email.</param>
    /// <param name="subject">The subject of the email.</param>
    /// <param name="messagebody">The message body.</param>
    public async Task RequestNewEmail(string address, string subject, string messagebody = "")
    {
            var emailIntent = new Intent(Intent.ActionSend);
            var recipients = new string[] { address };
            emailIntent.PutExtra(Intent.ExtraEmail, recipients);
            emailIntent.PutExtra(Intent.ExtraText, messagebody);
            emailIntent.PutExtra(Intent.ExtraSubject, subject);
            emailIntent.SetType("text/plain");

            Activity.StartActivity(Intent.CreateChooser(emailIntent, "Send mail..."));
        }
}