# Starter pipeline
name: 1.0.3.$(rev:r)

variables: 
- name: Project.Path
  value: src/PolyhydraGames.Core.Maui.csproj 
- name: Project.Config
  value: release
trigger:
  branches:
    include:
    - refs/heads/master
  paths:
    include:
    - src
jobs:
- job: Phase_1 
  cancelTimeoutInMinutes: 1
  
  pool:
    #vmImage: windows-latest
    name: Windows 
  steps:
  - checkout: self
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: restore
      projects: $(Project.Path)
      feedRestore: 015fc12f-cd63-4ab4-8d6a-dc889e53bf70
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '$(Project.Path)'
      arguments:  --no-restore
      configuration: $(Project.Config) 
  - task: DotNetCoreCLI@2
    displayName: dotnet build and pack
    inputs:
      command: pack
      packagesToPack: '$(Project.Path)' 
      versioningScheme: 'byBuildNumber'
      arguments: --configuration $(Project.Config) --no-build
  - task: NuGetCommand@2
    displayName: Poly NuGet push
    inputs:
      command: push
      feedPublish: 015fc12f-cd63-4ab4-8d6a-dc889e53bf70
      allowPackageConflicts: false
  - task: NuGetCommand@2
    displayName: NuGet.org push
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'Nuget Org'
  - task: ado-discord-webhook@1
    inputs:
      channelId: '1083779130576879656'
      webhookKey: 'QAhq2PpBl9iUSv51rQNPajpVZivOdj-hMcClCwHBz7OFdyxuI9Ni_Ykvglpxw53oDX9D'
      name: 'Polyhydra Build'
      avatar: 'https://scontent-iad3-1.xx.fbcdn.net/v/t39.30808-6/277759422_459407522643032_5740191239763665615_n.png?_nc_cat=109&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=Eh7rt73EuYcAX-1w6EJ&_nc_ht=scontent-iad3-1.xx&oh=00_AfA8K4k2WtaqlaA0CEznY-Hk2DZY3gsdDwPp-XOw3L1B3Q&oe=64121C61'
      messageType: 'content'
      content: 'PolyhydraGames.Core.Maui Completed Build: $(Build.BuildNumber)'

